/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:82573920-41e5-4c88-9464-628518156914",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_tRFhTtO5k",
    "aws_user_pools_web_client_id": "1d807s4hlgh5pig8vfb0ms11hv",
    "oauth": {},
    "aws_user_files_s3_bucket": "profilebucket162840-prod",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
